Repository AI-Jiwoo/Jiwoo-Back, pull requests merged in 2024-08, with the labels that each got.

#13 [Feature] BM 및 전략(2) 기능 구현 - (비즈니스모델 분석)
  src/main/java/org/jiwoo/back/accelerating/aggregate/vo/ResponseAnalyzeBusinessmodelVO.java
  src/main/java/org/jiwoo/back/accelerating/controller/BusinessmodelController.java
  src/main/java/org/jiwoo/back/accelerating/service/BusinessmodelService.java
  src/main/java/org/jiwoo/back/accelerating/service/BusinessmodelServiceImpl.java
  src/test/java/org/jiwoo/back/accelerating/service/BusinessmodelServiceImplTest.java
Labels: ✨feat, 🚥test

#14 [Feature] BM 및 전략(3) 기능 구현 - (비즈니스모델 제안)
  src/main/java/org/jiwoo/back/accelerating/aggregate/vo/BusinessProposalVO.java
  src/main/java/org/jiwoo/back/accelerating/controller/BusinessmodelController.java
  src/main/java/org/jiwoo/back/accelerating/service/BusinessmodelService.java
  src/main/java/org/jiwoo/back/accelerating/service/BusinessmodelServiceImpl.java
  src/test/java/org/jiwoo/back/accelerating/service/BusinessmodelServiceImplTest.java
Labels: ✨feat, 🚥test

#16 [Feature] 카테고리 전체 조회, 시장조사 이력 조회 구현 및 버그 수정
  src/main/java/org/jiwoo/back/accelerating/aggregate/entity/MarketResearch.java
  src/main/java/org/jiwoo/back/accelerating/aggregate/vo/ResponseMarketResearchHistoryVO.java
  src/main/java/org/jiwoo/back/accelerating/controller/MarketResearchController.java
  src/main/java/org/jiwoo/back/accelerating/dto/MarketResearchHistoryDTO.java
  src/main/java/org/jiwoo/back/accelerating/repository/MarketResearchRepository.java
  src/main/java/org/jiwoo/back/accelerating/service/MarketResearchService.java
  src/main/java/org/jiwoo/back/accelerating/service/MarketResearchServiceImpl.java
  src/main/java/org/jiwoo/back/category/controller/CategoryController.java
  src/main/java/org/jiwoo/back/category/repository/CategoryRepository.java
  src/main/java/org/jiwoo/back/category/service/CategoryService.java
  src/main/java/org/jiwoo/back/category/service/CategoryServiceImpl.java
  src/test/java/org/jiwoo/back/accelerating/service/MarketResearchServiceImplTest.java
  src/test/java/org/jiwoo/back/category/service/CategoryServiceImplTest.java
Labels: 🐞bug, ✨feat, 🚥test

#17 [Refactor] User 인증 방식 수정
  src/main/java/org/jiwoo/back/accelerating/service/MarketResearchServiceImpl.java
  src/main/java/org/jiwoo/back/business/controller/BusinessController.java
  src/main/java/org/jiwoo/back/business/repository/BusinessRepository.java
  src/main/java/org/jiwoo/back/business/service/BusinessService.java
  src/main/java/org/jiwoo/back/business/service/BusinessServiceImpl.java
  src/main/java/org/jiwoo/back/config/MyBatisConfig.java
  src/test/java/org/jiwoo/back/business/service/BusinessServiceImplTest.java
Labels: 🚥test, 🔨refactor

#18 [CICD] EC2에 Java Server 배포 WorkFlow 구현
  .github/workflows/deploy.yml
  .github/workflows/gradle.yml
  .gitignore
Labels: ✨feat, ⚙set

#19 [Feature] 지원 사업 추가 및 조회 기능 구현
  src/main/java/org/jiwoo/back/business/repository/BusinessRepository.java
  src/main/java/org/jiwoo/back/business/service/BusinessService.java
  src/main/java/org/jiwoo/back/business/service/BusinessServiceImpl.java
  src/main/java/org/jiwoo/back/supprotProgram/aggregate/dto/SupportProgramDTO.java
  src/main/java/org/jiwoo/back/supprotProgram/aggregate/entity/SupportProgram.java
  src/main/java/org/jiwoo/back/supprotProgram/aggregate/entity/SupportProgramBusiness.java
  src/main/java/org/jiwoo/back/supprotProgram/aggregate/vo/MessageResponseVO.java
  src/main/java/org/jiwoo/back/supprotProgram/aggregate/vo/SupportProgramRequestVO.java
  src/main/java/org/jiwoo/back/supprotProgram/aggregate/vo/SupportProgramResponseVO.java
  src/main/java/org/jiwoo/back/supprotProgram/controller/SupportProgramController.java
  src/main/java/org/jiwoo/back/supprotProgram/repository/SupportProgramBusinessRepository.java
  src/main/java/org/jiwoo/back/supprotProgram/repository/SupportProgramRepository.java
  src/main/java/org/jiwoo/back/supprotProgram/service/SupportProgramService.java
  src/main/java/org/jiwoo/back/supprotProgram/service/SupportProgramServiceImpl.java
  src/test/java/org/jiwoo/back/supprotProgram/service/SupportProgramServiceTest.java
Labels: ✨feat

#21 [Refactor] 버그 수정을 위한 logging 추가
  src/main/java/org/jiwoo/back/supprotProgram/service/SupportProgramServiceImpl.java
Labels: 🐞bug, 🔨refactor

#22 [Fix] VectorDB, RDBMS 데이터 불일치로 인한 버그 수정
  src/main/java/org/jiwoo/back/supprotProgram/service/SupportProgramServiceImpl.java
Labels: 🐞bug, 🔨refactor

#23 [Fix] VectorDB, RDBMS 데이터 불일치로 인한 버그 수정(2)
  src/main/java/org/jiwoo/back/supprotProgram/service/SupportProgramServiceImpl.java
Labels: 🐞bug

#24 [Feature] 홈택스 API 조회 기능 구현
  build.gradle
  src/main/java/org/jiwoo/back/config/RestTemplateConfig.java
  src/main/java/org/jiwoo/back/taxation/aggregate/entity/Taxation.java
  src/main/java/org/jiwoo/back/taxation/aggregate/vo/ResponseTaxationVO.java
  src/main/java/org/jiwoo/back/taxation/controller/TaxationController.java
  src/main/java/org/jiwoo/back/taxation/dto/TaxationDTO.java
  src/main/java/org/jiwoo/back/taxation/repository/TaxationRepository.java
  src/main/java/org/jiwoo/back/taxation/service/HomeTaxAPIService.java
  src/main/java/org/jiwoo/back/taxation/service/HomeTaxAPIServiceImpl.java
  src/test/java/org/jiwoo/back/taxaxtion/service/HomeTaxAPIServiceTest.java
Labels: ✨feat, 🔨refactor

#25 [Release] 세무업무 간소화 기능 업데이트
  build.gradle
  src/main/java/org/jiwoo/back/config/RestTemplateConfig.java
  src/main/java/org/jiwoo/back/taxation/aggregate/entity/Taxation.java
  src/main/java/org/jiwoo/back/taxation/aggregate/vo/ResponseTaxationVO.java
  src/main/java/org/jiwoo/back/taxation/controller/TaxationController.java
  src/main/java/org/jiwoo/back/taxation/dto/TaxationDTO.java
  src/main/java/org/jiwoo/back/taxation/repository/TaxationRepository.java
  src/main/java/org/jiwoo/back/taxation/service/HomeTaxAPIService.java
  src/main/java/org/jiwoo/back/taxation/service/HomeTaxAPIServiceImpl.java
  src/test/java/org/jiwoo/back/taxaxtion/service/HomeTaxAPIServiceTest.java
Labels: ✨feat
