Repository AI-Jiwoo/Jiwoo-Back, pull requests merged in 2024-07, with the labels that each got.

#1 [Feature] OpenAI API 요청 공통 모듈 구현
  build.gradle
  src/main/java/org/jiwoo/back/common/OpenAI/dto/Message.java
  src/main/java/org/jiwoo/back/common/OpenAI/dto/OpenAIRequestDTO.java
  src/main/java/org/jiwoo/back/common/OpenAI/dto/OpenAIResponseDTO.java
  src/main/java/org/jiwoo/back/common/OpenAI/service/OpenAIService.java
  src/main/java/org/jiwoo/back/common/OpenAI/service/OpenAIServiceImpl.java
  src/main/java/org/jiwoo/back/common/exception/CustomException.java
  src/main/java/org/jiwoo/back/common/exception/OpenAIResponseFailException.java
  src/main/java/org/jiwoo/back/config/OpenAIConfig.java
  src/test/java/org/jiwoo/back/common/OpenAIServiceTest.java
Labels: enhancement

#4 [Feature] 시장조사 진입 시, 사업정보 불러오기 기능 구현
  build.gradle
  gradlew
  gradlew.bat
  src/main/java/org/jiwoo/back/business/aggregate/entity/Business.java
  src/main/java/org/jiwoo/back/business/aggregate/vo/ResponseBusinessVO.java
  src/main/java/org/jiwoo/back/business/controller/BusinessController.java
  src/main/java/org/jiwoo/back/business/dto/BusinessDTO.java
  src/main/java/org/jiwoo/back/business/repository/BusinessMapper.java
  src/main/java/org/jiwoo/back/business/service/BusinessService.java
  src/main/java/org/jiwoo/back/business/service/BusinessServiceImpl.java
  src/main/java/org/jiwoo/back/config/MyBatisConfig.java
  src/main/resources/org/jiwoo/back/business/repository/BusinessMapper.xml
  src/test/java/org/jiwoo/back/business/service/BusinessServiceImplTest.java
Labels: ✨feat

#5 [Feature] 회원가입, 로그인 구현
  build.gradle
  src/main/java/org/jiwoo/back/common/exception/GlobalExceptionHandler.java
  src/main/java/org/jiwoo/back/common/exception/UserEmailDuplicateException.java
  src/main/java/org/jiwoo/back/common/filter/JwtFilter.java
  src/main/java/org/jiwoo/back/common/filter/LoginFilter.java
  src/main/java/org/jiwoo/back/common/util/JwtUtil.java
  src/main/java/org/jiwoo/back/common/util/RegularExpression.java
  src/main/java/org/jiwoo/back/config/SecurityConfig.java
  src/main/java/org/jiwoo/back/user/aggregate/entity/User.java
  src/main/java/org/jiwoo/back/user/aggregate/enums/UserRole.java
  src/main/java/org/jiwoo/back/user/aggregate/enums/UserRoleConverter.java
  src/main/java/org/jiwoo/back/user/aggregate/vo/MessageResponseVO.java
  src/main/java/org/jiwoo/back/user/aggregate/vo/SignupRequestVO.java
  src/main/java/org/jiwoo/back/user/controller/AuthController.java
  src/main/java/org/jiwoo/back/user/dto/AuthDTO.java
  src/main/java/org/jiwoo/back/user/dto/CustomUserDetails.java
  src/main/java/org/jiwoo/back/user/repository/UserRepository.java
  src/main/java/org/jiwoo/back/user/service/AuthService.java
  src/main/java/org/jiwoo/back/user/service/AuthServiceImpl.java
  src/main/java/org/jiwoo/back/user/service/CustomUserDetailsService.java
  src/test/java/org/jiwoo/back/user/service/AuthServiceTest.java
Labels: ✨feat, ⚙set

#6 [Refactor] 시장조사 진입 시, 사업정보 불러오기 기능 구현
  src/main/java/org/jiwoo/back/business/aggregate/entity/Business.java
  src/main/java/org/jiwoo/back/business/aggregate/vo/ResponseBusinessVO.java
  src/main/java/org/jiwoo/back/business/dto/BusinessDTO.java
  src/main/java/org/jiwoo/back/business/repository/BusinessMapper.java
  src/main/java/org/jiwoo/back/business/repository/BusinessRepository.java
  src/main/java/org/jiwoo/back/business/service/BusinessService.java
  src/main/java/org/jiwoo/back/business/service/BusinessServiceImpl.java
  src/main/resources/org/jiwoo/back/business/repository/BusinessMapper.xml
  src/test/java/org/jiwoo/back/business/service/BusinessServiceImplTest.java
Labels: 🔨refactor

#7 [Feature] 회원 정보 변경, 비밀번호 변경, 내 프로필 조회 기능 구현
  src/main/java/org/jiwoo/back/common/exception/NotLoggedInException.java
  src/main/java/org/jiwoo/back/common/exception/NotMatchedPasswordException.java
  src/main/java/org/jiwoo/back/common/filter/JwtFilter.java
  src/main/java/org/jiwoo/back/user/aggregate/entity/User.java
  src/main/java/org/jiwoo/back/user/aggregate/vo/CurrentUserResponseVO.java
  src/main/java/org/jiwoo/back/user/aggregate/vo/EditPasswordRequestVO.java
  src/main/java/org/jiwoo/back/user/aggregate/vo/EditUserInfoRequestVO.java
  src/main/java/org/jiwoo/back/user/controller/AuthController.java
  src/main/java/org/jiwoo/back/user/dto/CurrentUserDTO.java
  src/main/java/org/jiwoo/back/user/dto/EditPasswordDTO.java
  src/main/java/org/jiwoo/back/user/service/AuthService.java
  src/main/java/org/jiwoo/back/user/service/AuthServiceImpl.java
  src/test/java/org/jiwoo/back/user/service/AuthServiceTest.java
Labels: ✨feat, 🚥test, 🔨refactor

#8 [Feature] 시장 조사(1) 기능 구현 - (사업정보 기반시장 규모, 성장률)
  build.gradle
  src/main/java/org/jiwoo/back/business/aggregate/entity/Business.java
  src/main/java/org/jiwoo/back/business/aggregate/entity/BusinessCategory.java
  src/main/java/org/jiwoo/back/business/dto/BusinessCategoryDTO.java
  src/main/java/org/jiwoo/back/business/dto/BusinessDTO.java
  src/main/java/org/jiwoo/back/business/service/BusinessServiceImpl.java
  src/main/java/org/jiwoo/back/category/aggregate/entity/Category.java
  src/main/java/org/jiwoo/back/category/repository/CategoryRepository.java
  src/main/java/org/jiwoo/back/category/service/CategoryService.java
  src/main/java/org/jiwoo/back/category/service/CategoryServiceImpl.java
  src/main/java/org/jiwoo/back/marketresearch/aggregate/entity/MarketResearch.java
  src/main/java/org/jiwoo/back/marketresearch/aggregate/vo/ResponseMarketResearchVO.java
  src/main/java/org/jiwoo/back/marketresearch/controller/MarketResearchController.java
  src/main/java/org/jiwoo/back/marketresearch/dto/MarketSizeGrowthDTO.java
  src/main/java/org/jiwoo/back/marketresearch/service/MarketResearchService.java
  src/main/java/org/jiwoo/back/marketresearch/service/MarketResearchServiceImpl.java
  src/test/java/org/jiwoo/back/business/service/BusinessServiceImplTest.java
  src/test/java/org/jiwoo/back/category/service/CategoryServiceImplTest.java
  src/test/java/org/jiwoo/back/marketresearch/service/MarketResearchServiceImplTest.java
Labels: ✨feat, 🚥test, 🔨refactor, ⚙set

#10 [Feature] 사업정보 저장 기능, 사용자의 사업목록 조회 기능 구현
  src/main/java/org/jiwoo/back/business/aggregate/entity/Business.java
  src/main/java/org/jiwoo/back/business/aggregate/entity/StartupStage.java
  src/main/java/org/jiwoo/back/business/controller/BusinessController.java
  src/main/java/org/jiwoo/back/business/dto/BusinessDTO.java
  src/main/java/org/jiwoo/back/business/repository/BusinessRepository.java
  src/main/java/org/jiwoo/back/business/repository/StartupStageRepository.java
  src/main/java/org/jiwoo/back/business/service/BusinessService.java
  src/main/java/org/jiwoo/back/business/service/BusinessServiceImpl.java
  src/main/java/org/jiwoo/back/marketresearch/service/MarketResearchServiceImpl.java
  src/test/java/org/jiwoo/back/business/service/BusinessServiceImplTest.java
Labels: ✨feat, 🚥test
